<?php
/**
 * Created by PhpStorm.
 * User: hesam
 * Date: 9/19/19
 * Time: 11:56 AM
 */

namespace Repository;


use App\Builders\UserBuilder;
use App\Repositories\UserRepository;
use App\Repositories\UserRepositoryImp;
use App\User;
use Carbon\Carbon;
use Tests\TestCase;

class UserRepositoryTest extends TestCase
{
    /**
     * @var UserRepositoryImp
     */
    private $user_repo;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user_repo = new UserRepository(new User(), new UserBuilder(new User()));
    }

    public function test_give_users_invite_active_users()
    {
        $res = $this->user_repo->getUsersThatInvitedOtherActiveUser();
        dd($res);
    }
}
